<?php

declare(strict_types=1);

namespace Akumi\Sdk\Resources;

use Akumi\Sdk\Client\Transport;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class AgentsResource
{
    public function __construct(private readonly Transport $transport) {}

    /**
     * @return array<string, mixed>
     */
    public function v1AgentsIndex(): array
    {
        return $this->transport->send('GET', '/agents', null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function v1AgentsStore(array $params = []): array
    {
        return $this->transport->send('POST', '/agents', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function v1AgentsRunsShow(string $run): array
    {
        return $this->transport->send('GET', '/agents/runs/' . $run, null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function v1AgentsShow(string $agent): array
    {
        return $this->transport->send('GET', '/agents/' . $agent, null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function v1AgentsUpdate(string $agent, array $params = []): array
    {
        return $this->transport->send('PATCH', '/agents/' . $agent, null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function v1AgentsVersionsIndex(string $agent): array
    {
        return $this->transport->send('GET', '/agents/' . $agent . '/versions', null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function v1AgentsVersionsStore(string $agent, array $params = []): array
    {
        return $this->transport->send('POST', '/agents/' . $agent . '/versions', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function v1AgentsVersionsShow(string $agent, int $version): array
    {
        return $this->transport->send('GET', '/agents/' . $agent . '/versions/' . $version, null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function v1AgentsRunsStore(string $agent, array $params = []): array
    {
        return $this->transport->send('POST', '/agents/' . $agent . '/runs', null, $params);
    }
}
