<?php

declare(strict_types=1);

namespace Akumi\Sdk\Resources;

use Akumi\Sdk\Client\Transport;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class AuditLogsResource
{
    public function __construct(private readonly Transport $transport) {}

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function list(array $query = []): array
    {
        return $this->transport->send('GET', '/audit-logs', $query, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function get(string $uuid): array
    {
        return $this->transport->send('GET', '/audit-logs/' . $uuid, null, null);
    }
}
