<?php

declare(strict_types=1);

namespace Akumi\Sdk\Resources;

use Akumi\Sdk\Client\Transport;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class EmbeddingsResource
{
    public function __construct(private readonly Transport $transport) {}

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function create(array $params = []): array
    {
        return $this->transport->send('POST', '/embeddings', null, $params);
    }
}
