<?php

declare(strict_types=1);

namespace Akumi\Sdk\Resources;

use Akumi\Sdk\Client\Transport;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class MemoryResource
{
    public function __construct(private readonly Transport $transport) {}

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function search(array $params = []): array
    {
        return $this->transport->send('POST', '/memory/search', null, $params);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function listFacts(array $query = []): array
    {
        return $this->transport->send('GET', '/memory/facts', $query, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function rememberFact(array $params = []): array
    {
        return $this->transport->send('POST', '/memory/facts', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function forgetFact(string $id): array
    {
        return $this->transport->send('DELETE', '/memory/facts/' . $id, null, null);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function export(array $query = []): array
    {
        return $this->transport->send('GET', '/memory/export', $query, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function erase(): array
    {
        return $this->transport->send('DELETE', '/memory', null, null);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function listDocuments(array $query = []): array
    {
        return $this->transport->send('GET', '/memory/documents', $query, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function ingestDocument(array $params = []): array
    {
        return $this->transport->send('POST', '/memory/documents', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function getDocument(string $document): array
    {
        return $this->transport->send('GET', '/memory/documents/' . $document, null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function deleteDocument(string $document): array
    {
        return $this->transport->send('DELETE', '/memory/documents/' . $document, null, null);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function listCollections(array $query = []): array
    {
        return $this->transport->send('GET', '/memory/collections', $query, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function createCollection(array $params = []): array
    {
        return $this->transport->send('POST', '/memory/collections', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function getCollection(string $slug): array
    {
        return $this->transport->send('GET', '/memory/collections/' . $slug, null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function deleteCollection(string $slug): array
    {
        return $this->transport->send('DELETE', '/memory/collections/' . $slug, null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function updateCollection(string $slug, array $params = []): array
    {
        return $this->transport->send('PATCH', '/memory/collections/' . $slug, null, $params);
    }
}
