<?php

declare(strict_types=1);

namespace Akumi\Sdk\Resources;

use Akumi\Sdk\Client\Transport;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class MemoryResource
{
    public function __construct(private readonly Transport $transport) {}

    /**
     * @return array<string, mixed>
     */
    public function forget(): array
    {
        return $this->transport->send('DELETE', '/memory', null, null);
    }
}
