<?php

declare(strict_types=1);

namespace Akumi\Sdk\Resources;

use Akumi\Sdk\Client\Transport;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class MemoryThreadsResource
{
    public function __construct(private readonly Transport $transport) {}

    /**
     * @return array<string, mixed>
     */
    public function list(): array
    {
        return $this->transport->send('GET', '/memory/threads', null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function create(): array
    {
        return $this->transport->send('POST', '/memory/threads', null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function get(string $thread): array
    {
        return $this->transport->send('GET', '/memory/threads/' . $thread, null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function delete(string $thread): array
    {
        return $this->transport->send('DELETE', '/memory/threads/' . $thread, null, null);
    }
}
