<?php

declare(strict_types=1);

namespace Akumi\Sdk\Resources;

use Akumi\Sdk\Client\Transport;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class RecallResource
{
    public function __construct(private readonly Transport $transport) {}

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function listThreads(array $query = []): array
    {
        return $this->transport->send('GET', '/recall/threads', $query, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function createThread(): array
    {
        return $this->transport->send('POST', '/recall/threads', null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function getThread(string $thread): array
    {
        return $this->transport->send('GET', '/recall/threads/' . $thread, null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function deleteThread(string $thread): array
    {
        return $this->transport->send('DELETE', '/recall/threads/' . $thread, null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function search(array $params = []): array
    {
        return $this->transport->send('POST', '/recall/search', null, $params);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function searchFacts(array $params = []): array
    {
        return $this->transport->send('POST', '/recall/facts/search', null, $params);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function listFacts(array $query = []): array
    {
        return $this->transport->send('GET', '/recall/facts', $query, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function rememberFact(array $params = []): array
    {
        return $this->transport->send('POST', '/recall/facts', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function forgetFact(string $id): array
    {
        return $this->transport->send('DELETE', '/recall/facts/' . $id, null, null);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function export(array $query = []): array
    {
        return $this->transport->send('GET', '/recall/export', $query, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function erase(): array
    {
        return $this->transport->send('DELETE', '/recall', null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function searchDocuments(array $params = []): array
    {
        return $this->transport->send('POST', '/recall/documents/search', null, $params);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function listDocuments(array $query = []): array
    {
        return $this->transport->send('GET', '/recall/documents', $query, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function ingestDocument(array $params = []): array
    {
        return $this->transport->send('POST', '/recall/documents', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function getDocument(string $document): array
    {
        return $this->transport->send('GET', '/recall/documents/' . $document, null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function deleteDocument(string $document): array
    {
        return $this->transport->send('DELETE', '/recall/documents/' . $document, null, null);
    }

    /**
     * @param  array<string, mixed>  $query
     * @return array<string, mixed>
     */
    public function listCollections(array $query = []): array
    {
        return $this->transport->send('GET', '/recall/collections', $query, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function createCollection(array $params = []): array
    {
        return $this->transport->send('POST', '/recall/collections', null, $params);
    }

    /**
     * @return array<string, mixed>
     */
    public function getCollection(string $slug): array
    {
        return $this->transport->send('GET', '/recall/collections/' . $slug, null, null);
    }

    /**
     * @return array<string, mixed>
     */
    public function deleteCollection(string $slug): array
    {
        return $this->transport->send('DELETE', '/recall/collections/' . $slug, null, null);
    }

    /**
     * @param  array<string, mixed>  $params
     * @return array<string, mixed>
     */
    public function updateCollection(string $slug, array $params = []): array
    {
        return $this->transport->send('PATCH', '/recall/collections/' . $slug, null, $params);
    }
}
