<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class AuditLogApiResource
{
    public function __construct(
        public readonly string $id,
        public readonly string $component,
        public readonly string $action,
        public readonly ?int $actor_id,
        public readonly ?string $ip_address,
        public readonly ?string $user_agent,
        public readonly mixed $target,
        public readonly mixed $metadata,
        public readonly ?string $created_at,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            component: $data['component'],
            action: $data['action'],
            actor_id: $data['actor_id'],
            ip_address: $data['ip_address'],
            user_agent: $data['user_agent'],
            target: $data['target'],
            metadata: $data['metadata'],
            created_at: $data['created_at'],
        );
    }
}
