<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class AuditLogApiResource
{
    public function __construct(
        public readonly string $id,
        public readonly string $component,
        public readonly string $action,
        public readonly ?int $actorId,
        public readonly ?string $ipAddress,
        public readonly ?string $userAgent,
        public readonly mixed $target,
        public readonly mixed $metadata,
        public readonly ?string $createdAt,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            component: $data['component'],
            action: $data['action'],
            actorId: $data['actorId'],
            ipAddress: $data['ipAddress'],
            userAgent: $data['userAgent'],
            target: $data['target'],
            metadata: $data['metadata'],
            createdAt: $data['createdAt'],
        );
    }
}
