<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class ChatCompletionsRequest
{
    public function __construct(
        public readonly string $model,
        public readonly array $messages,
        public readonly ?float $temperature = null,
        public readonly ?int $max_tokens = null,
        public readonly ?bool $stream = null,
        public readonly ?bool $firewall = null,
        public readonly ?string $rag = null,
        public readonly ?string $user = null,
        public readonly ?string $thread = null,
        public readonly ?float $top_p = null,
        public readonly ?float $presence_penalty = null,
        public readonly ?float $frequency_penalty = null,
        public readonly ?int $n = null,
        public readonly ?int $seed = null,
        public readonly ?bool $logprobs = null,
        public readonly ?int $top_logprobs = null,
        public readonly ?int $max_completion_tokens = null,
        public readonly ?string $tool_choice = null,
        public readonly ?bool $parallel_tool_calls = null,
        public readonly ?bool $cache = null,
        public readonly ?array $stop = null,
        public readonly ?array $logit_bias = null,
        public readonly mixed $response_format = null,
        public readonly ?array $tools = null,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            model: $data['model'],
            messages: $data['messages'],
            temperature: $data['temperature'] ?? null,
            max_tokens: $data['max_tokens'] ?? null,
            stream: $data['stream'] ?? null,
            firewall: $data['firewall'] ?? null,
            rag: $data['rag'] ?? null,
            user: $data['user'] ?? null,
            thread: $data['thread'] ?? null,
            top_p: $data['top_p'] ?? null,
            presence_penalty: $data['presence_penalty'] ?? null,
            frequency_penalty: $data['frequency_penalty'] ?? null,
            n: $data['n'] ?? null,
            seed: $data['seed'] ?? null,
            logprobs: $data['logprobs'] ?? null,
            top_logprobs: $data['top_logprobs'] ?? null,
            max_completion_tokens: $data['max_completion_tokens'] ?? null,
            tool_choice: $data['tool_choice'] ?? null,
            parallel_tool_calls: $data['parallel_tool_calls'] ?? null,
            cache: $data['cache'] ?? null,
            stop: $data['stop'] ?? null,
            logit_bias: $data['logit_bias'] ?? null,
            response_format: $data['response_format'] ?? null,
            tools: $data['tools'] ?? null,
        );
    }
}
