<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class EmbeddingsRequest
{
    public function __construct(
        public readonly string $model,
        public readonly array $input,
        public readonly ?string $encoding_format = null,
        public readonly ?int $dimensions = null,
        public readonly ?string $user = null,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            model: $data['model'],
            input: $data['input'],
            encoding_format: $data['encoding_format'] ?? null,
            dimensions: $data['dimensions'] ?? null,
            user: $data['user'] ?? null,
        );
    }
}
