<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class IngestDocumentRequest
{
    public function __construct(
        public readonly string $title,
        public readonly string $text,
        public readonly string $collection,
        public readonly ?string $source = null,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            title: $data['title'],
            text: $data['text'],
            collection: $data['collection'],
            source: $data['source'] ?? null,
        );
    }
}
