<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class RememberFactRequest
{
    public function __construct(
        public readonly string $content,
        public readonly string $user_ref,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            content: $data['content'],
            user_ref: $data['user_ref'],
        );
    }
}
