<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class SearchFactsRequest
{
    public function __construct(
        public readonly string $query,
        public readonly ?array $collection = null,
        public readonly ?string $user_ref = null,
        public readonly ?int $limit = null,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            query: $data['query'],
            collection: $data['collection'] ?? null,
            user_ref: $data['user_ref'] ?? null,
            limit: $data['limit'] ?? null,
        );
    }
}
