<?php

declare(strict_types=1);

namespace Akumi\Sdk\Models;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class StoreScoreRequest
{
    public function __construct(
        public readonly string $request_id,
        public readonly string $name,
        public readonly ?float $value = null,
        public readonly ?string $value_string = null,
        public readonly ?string $comment = null,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            request_id: $data['request_id'],
            name: $data['name'],
            value: $data['value'] ?? null,
            value_string: $data['value_string'] ?? null,
            comment: $data['comment'] ?? null,
        );
    }
}
