<?php

declare(strict_types=1);

namespace Akumi\Sdk;

use Akumi\Sdk\Client\Config;
use Akumi\Sdk\Client\Transport;
use Akumi\Sdk\Resources\RecallResource;
use Akumi\Sdk\Resources\AuditLogsResource;
use Akumi\Sdk\Resources\ChatResource;
use Akumi\Sdk\Resources\EmbeddingsResource;
use Akumi\Sdk\Resources\ModelsResource;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class Akumi
{
    private readonly Transport $transport;

    public readonly RecallResource $recall;

    public readonly AuditLogsResource $auditLogs;

    public readonly ChatResource $chat;

    public readonly EmbeddingsResource $embeddings;

    public readonly ModelsResource $models;

    public function __construct(Config $config)
    {
        $this->transport = new Transport($config);
        $this->recall = new RecallResource($this->transport);
        $this->auditLogs = new AuditLogsResource($this->transport);
        $this->chat = new ChatResource($this->transport);
        $this->embeddings = new EmbeddingsResource($this->transport);
        $this->models = new ModelsResource($this->transport);
    }

    public static function fromApiKey(string $apiKey): self
    {
        return new self(new Config(apiKey: $apiKey));
    }
}
