<?php

declare(strict_types=1);

namespace Akumi\Sdk;

use Akumi\Sdk\Client\Config;
use Akumi\Sdk\Client\Transport;
use Akumi\Sdk\Resources\AuditLogsResource;
use Akumi\Sdk\Resources\ChatResource;
use Akumi\Sdk\Resources\ModelsResource;
use Akumi\Sdk\Resources\MemoryResource;
use Akumi\Sdk\Resources\MemoryThreadsResource;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class Akumi
{
    private readonly Transport $transport;

    public readonly AuditLogsResource $auditLogs;

    public readonly ChatResource $chat;

    public readonly ModelsResource $models;

    public readonly MemoryResource $memory;

    public readonly MemoryThreadsResource $memoryThreads;

    public function __construct(Config $config)
    {
        $this->transport = new Transport($config);
        $this->auditLogs = new AuditLogsResource($this->transport);
        $this->chat = new ChatResource($this->transport);
        $this->models = new ModelsResource($this->transport);
        $this->memory = new MemoryResource($this->transport);
        $this->memoryThreads = new MemoryThreadsResource($this->transport);
    }

    public static function fromApiKey(string $apiKey): self
    {
        return new self(new Config(apiKey: $apiKey));
    }
}
