<?php

declare(strict_types=1);

namespace Akumi\Sdk;

use Akumi\Sdk\Client\Config;
use Akumi\Sdk\Client\Transport;
use Akumi\Sdk\Resources\AuditLogResource;
use Akumi\Sdk\Resources\ChatCompletionsResource;
use Akumi\Sdk\Resources\EmbeddingsResource;
use Akumi\Sdk\Resources\ModelsResource;
use Akumi\Sdk\Resources\RecallResource;
use Akumi\Sdk\Resources\ScoresResource;

// AUTO-GENERATED by akumi/codegen. Do not edit by hand.
final class Akumi
{
    private readonly Transport $transport;

    public readonly AuditLogResource $auditLog;

    public readonly ChatCompletionsResource $chatCompletions;

    public readonly EmbeddingsResource $embeddings;

    public readonly ModelsResource $models;

    public readonly RecallResource $recall;

    public readonly ScoresResource $scores;

    public function __construct(Config $config)
    {
        $this->transport = new Transport($config);
        $this->auditLog = new AuditLogResource($this->transport);
        $this->chatCompletions = new ChatCompletionsResource($this->transport);
        $this->embeddings = new EmbeddingsResource($this->transport);
        $this->models = new ModelsResource($this->transport);
        $this->recall = new RecallResource($this->transport);
        $this->scores = new ScoresResource($this->transport);
    }

    public static function fromApiKey(string $apiKey): self
    {
        return new self(new Config(apiKey: $apiKey));
    }
}
